DROP TABLE IF EXISTS book; 

CREATE TABLE Book(
BOOKID NUMBER(4) NOT NULL,
BOOKNAME VARCHAR2(20) NOT NULL,
AUTHOR VARCHAR2(20) NOT NULL,
PRICE NUMBER(6,2) NOT NULL,
CONSTRAINT BOOK_PK PRIMARY KEY (BOOKID)
);